/** Minimal single-page PDF (Helvetica) — no external deps. */

function escapePdfText(text: string) {
  return text.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)')
}

function buildContentStream(lines: string[]): string {
  const ops: string[] = ['BT', '/F1 12 Tf', '50 780 Td', '16 TL']
  lines.forEach((line, i) => {
    if (i === 0) {
      ops.push(`(${escapePdfText(line)}) Tj`)
    } else {
      ops.push('T*', `(${escapePdfText(line)}) Tj`)
    }
  })
  ops.push('ET')
  return ops.join('\n')
}

export function buildReceiptPdfBlob(input: {
  schoolName: string
  receiptId: string
  amount: number
  date: string
  payerName?: string
  utr?: string
  ref?: string
}): Blob {
  const lines = [
    'Orbit · My School Companion',
    input.schoolName,
    '',
    'PAYMENT RECEIPT',
    '',
    `Receipt ID: ${input.receiptId}`,
    `Date: ${input.date}`,
    `Amount: INR ${input.amount.toLocaleString('en-IN')}`,
    input.payerName ? `Payer: ${input.payerName}` : '',
    input.utr ? `UTR: ${input.utr}` : '',
    input.ref ? `Reference: ${input.ref}` : '',
    '',
    'Status: Verified UPI / UTR settlement',
    'Gateway fee: INR 0',
    '',
    'This receipt was generated by Orbit.',
  ].filter((l) => l !== undefined)

  const stream = buildContentStream(lines)
  const streamBytes = new TextEncoder().encode(stream)

  const objects: string[] = []
  objects.push('1 0 obj<< /Type /Catalog /Pages 2 0 R >>endobj\n')
  objects.push('2 0 obj<< /Type /Pages /Kids [3 0 R] /Count 1 >>endobj\n')
  objects.push(
    '3 0 obj<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>endobj\n',
  )
  objects.push(
    `4 0 obj<< /Length ${streamBytes.length} >>stream\n${stream}\nendstream\nendobj\n`,
  )
  objects.push('5 0 obj<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>endobj\n')

  let pdf = '%PDF-1.4\n'
  const offsets: number[] = [0]
  for (const obj of objects) {
    offsets.push(pdf.length)
    pdf += obj
  }
  const xrefPos = pdf.length
  pdf += `xref\n0 ${objects.length + 1}\n`
  pdf += '0000000000 65535 f \n'
  for (let i = 1; i <= objects.length; i++) {
    pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`
  }
  pdf += `trailer<< /Size ${objects.length + 1} /Root 1 0 R >>\n`
  pdf += `startxref\n${xrefPos}\n%%EOF`

  return new Blob([pdf], { type: 'application/pdf' })
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.click()
  URL.revokeObjectURL(url)
}
