insert into public.pilot100_login_staging (email, role, display_name, student_id) values
('admin@pilot100.orbit.app', 'school', 'Pilot School Admin', null),
('teacher01@pilot100.orbit.app', 'teacher', 'Mrs. Kavitha Reddy', null),
('teacher02@pilot100.orbit.app', 'teacher', 'Mr. Arun Menon', null),
('teacher03@pilot100.orbit.app', 'teacher', 'Ms. Fatima Khan', null),
('teacher04@pilot100.orbit.app', 'teacher', 'Mr. Suresh Pillai', null),
('teacher05@pilot100.orbit.app', 'teacher', 'Mrs. Anjali Deshmukh', null),
('parent001@pilot100.orbit.app', 'parent', 'Suresh Rao', null),
('parent002@pilot100.orbit.app', 'parent', 'Lakshmi Iyer', null),
('parent003@pilot100.orbit.app', 'parent', 'D''Souza Guardian', null),
('parent004@pilot100.orbit.app', 'parent', 'Joseph Guardian', null),
('parent005@pilot100.orbit.app', 'parent', 'Al-Hassan Guardian', null),
('parent006@pilot100.orbit.app', 'parent', 'Chinnu Guardian', null),
('parent007@pilot100.orbit.app', 'parent', 'Test Guardian', null),
('parent008@pilot100.orbit.app', 'parent', 'O''Brien Guardian', null),
('parent009@pilot100.orbit.app', 'parent', 'Sen Guardian', null),
('parent010@pilot100.orbit.app', 'parent', 'Patel Guardian', null),
('parent011@pilot100.orbit.app', 'parent', 'Menon Guardian', null),
('parent012@pilot100.orbit.app', 'parent', 'Sharma Guardian', null),
('parent013@pilot100.orbit.app', 'parent', 'Agarwal Guardian', null),
('parent014@pilot100.orbit.app', 'parent', 'Sharma Guardian', null),
('parent015@pilot100.orbit.app', 'parent', 'Nair Guardian', null),
('parent016@pilot100.orbit.app', 'parent', 'Singh Guardian', null),
('parent017@pilot100.orbit.app', 'parent', 'Mukherjee Guardian', null),
('parent018@pilot100.orbit.app', 'parent', 'Sen Guardian', null),
('parent019@pilot100.orbit.app', 'parent', 'Patel Guardian', null),
('parent020@pilot100.orbit.app', 'parent', 'Joshi Guardian', null),
('parent021@pilot100.orbit.app', 'parent', 'Rao Guardian', null),
('parent022@pilot100.orbit.app', 'parent', 'Hegde Guardian', null),
('parent023@pilot100.orbit.app', 'parent', 'Agarwal Guardian', null),
('parent024@pilot100.orbit.app', 'parent', 'Sharma Guardian', null),
('parent025@pilot100.orbit.app', 'parent', 'Nair Guardian', null),
('parent026@pilot100.orbit.app', 'parent', 'Singh Guardian', null),
('parent027@pilot100.orbit.app', 'parent', 'Mukherjee Guardian', null),
('parent028@pilot100.orbit.app', 'parent', 'Kapoor Guardian', null),
('parent029@pilot100.orbit.app', 'parent', 'Pillai Guardian', null),
('parent030@pilot100.orbit.app', 'parent', 'Deshmukh Guardian', null),
('parent031@pilot100.orbit.app', 'parent', 'Sen Guardian', null),
('parent032@pilot100.orbit.app', 'parent', 'Kapoor Guardian', null),
('parent033@pilot100.orbit.app', 'parent', 'Pillai Guardian', null),
('parent034@pilot100.orbit.app', 'parent', 'Deshmukh Guardian', null)
on conflict (email) do update set role = excluded.role, display_name = excluded.display_name, student_id = excluded.student_id;
