/** The ONLY place icons are chosen. Components import from here, never from lucide-react directly. */
import {
  House,
  BookOpen,
  Sprout,
  User,
  Bell,
  Sun,
  Moon,
  LogOut,
  ArrowLeft,
  Compass,
  Users,
  Trophy,
  Briefcase,
  Clock,
  CalendarDays,
  Sparkles,
  Camera,
  Target,
  Video,
  ClipboardList,
  FileText,
  Lock,
  School,
  CircleCheck,
  Flame,
  TrendingUp,
  Pencil,
  MapPin,
  FlaskConical,
  ChartColumn,
  ChevronRight,
  ArrowRight,
  Check,
  Headset,
  MessageSquare,
  Info,
  Award,
  Star,
  Leaf,
  Music,
  Laptop,
  Palette,
  Calculator,
  Languages,
  Atom,
  Rocket,
  Dumbbell,
  Brain,
  Globe,
  Lightbulb,
} from 'lucide-react'

export const ICON = {
  tab: { home: House, learn: BookOpen, grow: Sprout, me: User },
  chrome: {
    bell: Bell,
    themeLight: Sun,
    themeDark: Moon,
    signOut: LogOut,
    chevron: ChevronRight,
    arrow: ArrowRight,
    back: ArrowLeft,
    check: Check,
  },
  meta: { time: Clock, date: CalendarDays, place: MapPin, teacher: User, questions: FileText },
  item: {
    class: Video,
    homework: ClipboardList,
    assessment: FileText,
    exam: FileText,
    event: CalendarDays,
    study: BookOpen,
    quiz: Target,
    resource: BookOpen,
  },
  tool: {
    askOrbit: Sparkles,
    scan: Camera,
    quiz: Target,
    syllabus: BookOpen,
    calendar: CalendarDays,
    progress: ChartColumn,
  },
  grow: {
    interests: Compass,
    clubs: Users,
    competitions: Trophy,
    skills: Briefcase,
    journey: ChartColumn,
  },
  stat: { homework: ClipboardList, classes: Video, assessment: FileText, streak: Trophy },
  me: {
    personal: User,
    school: School,
    security: Lock,
    notifications: Bell,
    tasks: CircleCheck,
    active: CalendarDays,
    improving: TrendingUp,
    overall: ChartColumn,
    edit: Pencil,
    help: Headset,
    feedback: MessageSquare,
    about: Info,
  },
  subject: {
    math: Calculator,
    science: Sprout,
    chemistry: FlaskConical,
    english: BookOpen,
    physics: Atom,
    languages: Languages,
    social: Globe,
    default: BookOpen,
  },
  interest: {
    science: Leaf,
    technology: Laptop,
    sports: Dumbbell,
    arts: Palette,
    music: Music,
    business: Briefcase,
    space: Rocket,
    writing: Pencil,
    robotics: Brain,
    default: Lightbulb,
  },
  badge: {
    streak: Flame,
    earlyBird: Sun,
    curious: Compass,
    homework: Star,
    nature: Leaf,
    team: Users,
    award: Award,
  },
} as const

export type SubjectKey = keyof typeof ICON.subject

export const TONE_BY_ITEM_TYPE = {
  class: 'blue',
  homework: 'green',
  assessment: 'amber',
  exam: 'amber',
  event: 'teal',
  study: 'purple',
  quiz: 'purple',
  resource: 'blue',
} as const
